#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          ${{ steps.python.outputs.python-path }} -m pip install --upgrade pip
          ${{ steps.python.outputs.python-path }} -m pip install python-qpid-proton
          ${{ steps.python.outputs.python-path }} -m pip install pytest pytest-timeout

      - name: Prepare test environment
        run: |
          mkdir -p ${PWD}/artemis-data/override
          mkdir -p ${PWD}/qpid-dispatch
          cp ${PWD}/tests/.broker-00.xml ${PWD}/artemis-data/override/broker-00.xml
          cp ${PWD}/tests/.qdrouterd.conf ${PWD}/qpid-dispatch/qdrouterd.conf
          docker pull vromero/activemq-artemis
          docker pull rhmessagingqe/qpid-dispatch:ubuntu1804
          docker run -v ${PWD}/artemis-data/override:/var/lib/artemis/etc-override:Z -p 5672:5672 -d vromero/activemq-artemis:2-latest
          docker run -v ${PWD}/qpid-dispatch:/var/lib/qdrouterd:Z -p 5673:5673 -d rhmessagingqe/qpid-dispatch:ubuntu1804
          docker ps -a

      - name: Install
        run: ${{ steps.python.outputs.python-path }} -m pip install .

      - name: Test
        run: |
          cd tests
          ${{ steps.python.outputs.python-path }} test_integration.py
